'use strict';
// 탑뷰/후방 항해, 등대·등명기 점멸, 미니맵 렌더링
// TOP VIEW TRANSFORM / RENDER
function topTransform(wx, wy) { let angle = 0, cx = cam.x, cy = cam.y, zoom = cam.zoom, screenX = W * .5, screenY = H * .55; if (cameraMode === 0) angle = -Math.PI / 2 - cam.heading; else if (cameraMode === 1) angle = 0; const dx = wx - cx, dy = wy - cy, cs = Math.cos(angle), sn = Math.sin(angle); return { x: screenX + (dx * cs - dy * sn) * zoom, y: screenY + (dx * sn + dy * cs) * zoom, z: zoom, angle } }
function drawWaterTop(now) { const g = ctx.createLinearGradient(0, 0, 0, H); g.addColorStop(0, '#85d6ff'); g.addColorStop(.48, '#4eb0ef'); g.addColorStop(1, '#1679c8'); ctx.fillStyle = g; ctx.fillRect(0, 0, W, H); const shine = ctx.createRadialGradient(W * .78, H * .10, 0, W * .78, H * .10, 300); shine.addColorStop(0, 'rgba(255,247,191,.25)'); shine.addColorStop(1, 'rgba(255,247,191,0)'); ctx.fillStyle = shine; ctx.fillRect(0, 0, W, H) }
function drawRouteTop() { ctx.save(); ctx.lineCap = 'round'; ctx.lineJoin = 'round'; ctx.strokeStyle = 'rgba(255,255,255,.13)'; ctx.lineWidth = routeHalf * 2 * cam.zoom; ctx.beginPath(); route.forEach((p, i) => { const s = topTransform(p.x, p.y); i ? ctx.lineTo(s.x, s.y) : ctx.moveTo(s.x, s.y) }); ctx.stroke(); ctx.strokeStyle = 'rgba(110,245,205,.34)'; ctx.lineWidth = 10; ctx.setLineDash([28, 24]); ctx.beginPath(); route.forEach((p, i) => { const s = topTransform(p.x, p.y); i ? ctx.lineTo(s.x, s.y) : ctx.moveTo(s.x, s.y) }); ctx.stroke(); ctx.setLineDash([]); ctx.restore() }
function drawIslandTop(o) {
  const p = topTransform(o.x, o.y), rx = o.rx * cam.zoom, ry = o.ry * cam.zoom;
  if (p.x + rx < -100 || p.x - rx > W + 100 || p.y + ry < -100 || p.y - ry > H + 100) return;
  ctx.save(); ctx.translate(p.x, p.y); ctx.rotate(o.a + (cameraMode === 0 ? (-Math.PI / 2 - cam.heading) : 0));
  ctx.fillStyle = 'rgba(40,73,42,.20)'; ctx.beginPath(); ctx.ellipse(24, 34, rx * 1.03, ry * 1.03, 0, 0, TAU); ctx.fill();
  ctx.fillStyle = '#8ad567'; ctx.beginPath(); ctx.ellipse(0, 0, rx, ry, 0, 0, TAU); ctx.fill();
  ctx.fillStyle = '#f0dc8b'; ctx.beginPath(); ctx.ellipse(0, 0, rx * .88, ry * .88, 0, 0, TAU); ctx.fill();
  ctx.fillStyle = '#7bc45a'; ctx.beginPath(); ctx.ellipse(-rx * .08, -ry * .08, rx * .74, ry * .74, 0, 0, TAU); ctx.fill();
  // 섬 내부의 작은 나무 군락
  for (const tree of (o.trees || [])) {
    const tx = tree.lx * cam.zoom, ty = tree.ly * cam.zoom, s = clamp(15 * tree.size * cam.zoom, 5, 15);
    ctx.fillStyle = 'rgba(61,63,40,.75)'; ctx.fillRect(tx - s * .16, ty + s * .22, s * .32, s * .74);
    ctx.fillStyle = tree.shade ? '#2d874d' : '#3f9d58'; ctx.beginPath(); ctx.arc(tx, ty - s * .16, s * .74, 0, TAU); ctx.fill();
    ctx.fillStyle = tree.shade ? '#4fb66a' : '#62c875'; ctx.beginPath(); ctx.arc(tx - s * .24, ty - s * .42, s * .48, 0, TAU); ctx.fill();
    ctx.beginPath(); ctx.arc(tx + s * .28, ty - s * .36, s * .44, 0, TAU); ctx.fill();
  }
  ctx.restore()
}
function drawRockTop(r) { const p = topTransform(r.x, r.y), s = r.r * cam.zoom; if (p.x + s < 0 || p.x - s > W || p.y + s < 0 || p.y - s > H) return; ctx.fillStyle = 'rgba(0,0,0,.18)'; ctx.beginPath(); ctx.ellipse(p.x + 12, p.y + 12, s * .9, s * .52, 0, 0, TAU); ctx.fill(); ctx.fillStyle = r.central ? '#ff8a76' : '#8f969b'; ctx.beginPath(); ctx.ellipse(p.x, p.y, s, s * .68, .20, 0, TAU); ctx.fill(); ctx.fillStyle = r.central ? '#ffd1a8' : '#cbd0d4'; ctx.beginPath(); ctx.ellipse(p.x - s * .15, p.y - s * .1, s * .38, s * .18, .2, 0, TAU); ctx.fill() }
function drawBuoyTop(b, now) {
  const p = topTransform(b.x, b.y), s = clamp(cam.zoom * 1.2, .5, 1.2), col = b.side === 'red' ? '#ff666f' : '#45df87';
  const flash = navLightFlash(now, 0, 3600, 900);
  ctx.save(); ctx.fillStyle = '#ffffff'; rr(p.x - 10 * s, p.y - 32 * s, 20 * s, 38 * s, 7 * s); ctx.fill(); ctx.fillStyle = col; rr(p.x - 13 * s, p.y - 44 * s, 26 * s, 15 * s, 7 * s); ctx.fill();
  ctx.fillStyle = flash > .4 ? '#fffbd0' : '#5b6a72'; ctx.shadowColor = flash > .4 ? '#fff3a1' : 'transparent'; ctx.shadowBlur = flash > .4 ? 30 : 0; ctx.beginPath(); ctx.arc(p.x, p.y - 50 * s, 7 * s, 0, TAU); ctx.fill();
  if (flash > .4) { ctx.globalAlpha = .18 * flash; ctx.fillStyle = '#fff4a0'; ctx.beginPath(); ctx.arc(p.x, p.y - 50 * s, 35 * s, 0, TAU); ctx.fill() }
  ctx.restore()
}
function drawDangerMarkTop(m, now) { const p = topTransform(m.x, m.y), r = topTransform(m.rockX, m.rockY), s = clamp(cam.zoom * 1.25, .65, 1.18); ctx.save(); ctx.strokeStyle = 'rgba(255,226,122,.35)'; ctx.lineWidth = 3; ctx.setLineDash([8, 8]); ctx.beginPath(); ctx.moveTo(p.x, p.y); ctx.lineTo(r.x, r.y); ctx.stroke(); ctx.setLineDash([]); ctx.translate(p.x, p.y); ctx.shadowColor = 'rgba(255,211,90,.42)'; ctx.shadowBlur = 18; ctx.fillStyle = '#ffd25a'; rr(-12 * s, -14 * s, 24 * s, 28 * s, 8 * s); ctx.fill(); ctx.fillStyle = '#17223d'; ctx.fillRect(-4 * s, -39 * s, 8 * s, 25 * s); ctx.fillStyle = '#ffd25a'; ctx.beginPath(); ctx.moveTo(-10 * s, -39 * s); ctx.lineTo(0, -52 * s); ctx.lineTo(10 * s, -39 * s); ctx.closePath(); ctx.fill(); ctx.shadowBlur = 0; ctx.restore() }
function drawTargetTop(now) {
  const p = topTransform(goal.x, goal.y);
  if (goal.kind === 'landing') {
    ctx.save(); ctx.translate(p.x, p.y);
    // 실제로 멈춰 설 수 있는 선착장을 탑뷰에서 크게 표시합니다.
    ctx.fillStyle = 'rgba(255,255,255,.14)'; rr(-125, -60, 250, 120, 24); ctx.fill();
    ctx.fillStyle = '#7c5a3d'; rr(-105, -20, 210, 40, 8); ctx.fill();
    for (let i = -88; i <= 88; i += 32) { ctx.fillStyle = (i / 32) % 2 ? '#a77b53' : '#8b6546'; ctx.fillRect(i, -16, 24, 32) }
    ctx.fillStyle = '#e9f7ff'; rr(-62, -54, 124, 30, 10); ctx.fill(); text('정차 / 접안', 0, -34, 12, '#294468', 'center', 1000);
    ctx.strokeStyle = '#fff07a'; ctx.lineWidth = 4; ctx.setLineDash([10, 8]); ctx.beginPath(); ctx.arc(0, 0, 84, 0, TAU); ctx.stroke(); ctx.setLineDash([]);
    ctx.restore(); text(goal.name || '선착장', p.x, p.y + 70, 14, '#fff', 'center', 1000); return;
  }
  if (goal.kind === 'lighthouse') {
    const flash = targetLightFlash(now, 'lighthouse');
    ctx.save(); ctx.translate(p.x, p.y); ctx.fillStyle = '#ffffff'; rr(-20, -42, 40, 84, 10); ctx.fill(); ctx.fillStyle = '#ff686e'; rr(-26, -52, 52, 16, 8); ctx.fill();
    const lamp = flash > .18 ? '#fff5a0' : '#626b72'; ctx.fillStyle = lamp; ctx.shadowColor = flash > .18 ? '#ffe77d' : 'transparent'; ctx.shadowBlur = flash > .18 ? 38 * flash : 0; ctx.beginPath(); ctx.arc(0, -40, 10, 0, TAU); ctx.fill();
    if (flash > .18) { ctx.globalAlpha = .20 * flash; ctx.strokeStyle = '#fff0a0'; ctx.lineWidth = 18; ctx.beginPath(); ctx.arc(0, -40, 86 + Math.sin(now * .004) * 9, 0, TAU); ctx.stroke(); ctx.globalAlpha = .13 * flash; ctx.fillStyle = '#fff1a2'; ctx.beginPath(); ctx.moveTo(0, -40); ctx.lineTo(-150, -105); ctx.lineTo(-150, 25); ctx.closePath(); ctx.fill() }
    ctx.restore();
  } else {
    const flash = targetLightFlash(now, 'beacon');
    ctx.save(); ctx.translate(p.x, p.y); const col = goal.kind === 'install' ? '#ffd25a' : '#45df87'; ctx.fillStyle = '#fff'; rr(-8, -50, 16, 58, 7); ctx.fill();
    ctx.fillStyle = flash > .15 ? '#fff49b' : (goal.kind === 'install' ? col : '#5d6e67'); ctx.shadowColor = flash > .15 ? '#ffe57c' : 'transparent'; ctx.shadowBlur = flash > .15 ? 30 * flash : 0; ctx.beginPath(); ctx.arc(0, -56, 11, 0, TAU); ctx.fill(); ctx.shadowBlur = 0;
    if (flash > .15) { ctx.globalAlpha = .16 * flash; ctx.fillStyle = '#fff0a0'; ctx.beginPath(); ctx.arc(0, -56, 36, 0, TAU); ctx.fill() }
    if (goal.kind === 'install') { ctx.globalAlpha = 1; ctx.strokeStyle = 'rgba(255,210,90,.60)'; ctx.lineWidth = 4; ctx.setLineDash([8, 8]); ctx.beginPath(); ctx.arc(0, 0, 58, 0, TAU); ctx.stroke(); ctx.setLineDash([]) } ctx.restore()
  }
  text(goal.name, p.x, p.y + 68, 14, '#ffffff', 'center', 1000)
}
function drawShipTop() { const p = topTransform(ship.x, ship.y); let ang; if (cameraMode === 0) ang = 0; else ang = ship.heading + Math.PI / 2; ctx.save(); ctx.translate(p.x, p.y); ctx.rotate(ang); ctx.shadowColor = 'rgba(0,0,0,.24)'; ctx.shadowBlur = 16; ctx.fillStyle = 'rgba(0,0,0,.18)'; ctx.beginPath(); ctx.ellipse(10, 28, 44, 72, 0, 0, TAU); ctx.fill(); ctx.shadowBlur = 0; ctx.fillStyle = '#f6fbff'; ctx.beginPath(); ctx.moveTo(0, -86); ctx.lineTo(44, -30); ctx.lineTo(44, 46); ctx.quadraticCurveTo(0, 84, -44, 46); ctx.lineTo(-44, -30); ctx.closePath(); ctx.fill(); ctx.fillStyle = '#ffd25a'; rr(-20, -20, 40, 38, 10); ctx.fill(); ctx.fillStyle = '#2c4b8f'; rr(-16, -14, 32, 18, 6); ctx.fill(); ctx.fillStyle = '#3ad483'; rr(-42, 6, 10, 20, 4); ctx.fill(); ctx.fillStyle = '#ff666f'; rr(32, 6, 10, 20, 4); ctx.fill(); ctx.fillStyle = '#2b4570'; rr(-26, 26, 52, 22, 8); ctx.fill(); ctx.fillStyle = '#ffffff'; rr(-14, 32, 28, 10, 5); ctx.fill(); ctx.restore(); ctx.strokeStyle = 'rgba(255,255,255,.22)'; ctx.lineWidth = 3; ctx.beginPath(); ctx.moveTo(p.x, p.y - 96); ctx.lineTo(p.x, p.y - 156); ctx.stroke() }
function drawWakeTop() { for (const w of ship.wake) { const p = topTransform(w.x, w.y); ctx.globalAlpha = clamp(w.life, 0, 1) * .34; ctx.strokeStyle = '#d9f5ff'; ctx.lineWidth = clamp(w.size * cam.zoom * .42, 1, 6); ctx.beginPath(); ctx.arc(p.x, p.y, clamp(w.size * cam.zoom, 2, 22), 0, TAU); ctx.stroke() } ctx.globalAlpha = 1; for (const q of ship.particles) { const p = topTransform(q.x, q.y); ctx.globalAlpha = clamp(q.life, 0, 1) * .62; ctx.fillStyle = '#e8fbff'; ctx.beginPath(); ctx.arc(p.x, p.y, clamp(q.size * cam.zoom, 1, 8), 0, TAU); ctx.fill() } ctx.globalAlpha = 1 }
function drawFogTop() { const p = topTransform(fog.x, fog.y), r = fog.r * cam.zoom; if (r < 10) return; const g = ctx.createRadialGradient(p.x, p.y, r * .15, p.x, p.y, r); g.addColorStop(0, 'rgba(230,242,244,.35)'); g.addColorStop(.65, 'rgba(220,235,238,.20)'); g.addColorStop(1, 'rgba(220,235,238,0)'); ctx.fillStyle = g; ctx.beginPath(); ctx.arc(p.x, p.y, r, 0, TAU); ctx.fill() }
function drawArrivalCircle(wx, wy, radius, label, col = '#ffe47a') {
  const p = topTransform(wx, wy), r = radius * cam.zoom; ctx.save(); ctx.strokeStyle = col; ctx.lineWidth = 5; ctx.globalAlpha = .75; ctx.setLineDash([16, 13]); ctx.beginPath(); ctx.arc(p.x, p.y, r, 0, TAU); ctx.stroke(); ctx.setLineDash([]); ctx.fillStyle = col; ctx.globalAlpha = .11; ctx.beginPath(); ctx.arc(p.x, p.y, r, 0, TAU); ctx.fill(); ctx.globalAlpha = 1; text(label, p.x, p.y - r - 16, 12, '#fff', 'center', 1000); ctx.restore()
}
function drawMidRouteBeaconTop(now) { if (!midRouteBeacon) return; const p = topTransform(midRouteBeacon.x, midRouteBeacon.y), fixed = midRouteBeacon.status === 'fixed', fl = fixed ? navLightFlash(now, 0, 3600, 900) : faultyLightFlash(now, 500); ctx.save(); ctx.translate(p.x, p.y); ctx.fillStyle = '#fff'; rr(-9, -48, 18, 56, 7); ctx.fill(); ctx.fillStyle = '#ffcc58'; rr(-15, -58, 30, 14, 6); ctx.fill(); ctx.fillStyle = fl > .2 ? '#fff2a0' : '#596b70'; ctx.shadowColor = fl > .2 ? '#ffe57b' : 'transparent'; ctx.shadowBlur = fl > .2 ? 28 : 0; ctx.beginPath(); ctx.arc(0, -64, 10, 0, TAU); ctx.fill(); ctx.restore(); text(fixed ? '수리 완료 등표' : '고장 등표', p.x, p.y + 42, 13, fixed ? '#9af0c7' : '#ffd28a', 'center', 1000); if (!fixed) drawArrivalCircle(midRouteBeacon.x, midRouteBeacon.y, midRouteBeacon.arrivalRadius, '중간 등표 수리 구간', '#ffca67') }
function drawWeatherScreen(now) { if (!activeWeather) return; ctx.save(); if (activeWeather.type === 'fog') { ctx.fillStyle = 'rgba(225,238,242,.22)'; ctx.fillRect(0, 0, W, H); for (let i = 0; i < 8; i++) { ctx.fillStyle = `rgba(245,250,252,${.025 + i * .007})`; ctx.beginPath(); ctx.ellipse((i * 270 + now * .02) % 2200 - 100, 180 + i * 100, 300, 65, 0, 0, TAU); ctx.fill() } } else if (activeWeather.type === 'highwave') { ctx.strokeStyle = 'rgba(238,250,255,.07)'; ctx.lineWidth = 2; for (let y = 300; y < H; y += 300) { ctx.beginPath(); for (let x = -80; x < W + 100; x += 150)ctx.lineTo(x, y + Math.sin(x * .007 + now * .0018 + y) * 3); ctx.stroke() } } else if (activeWeather.type === 'storm') { ctx.fillStyle = 'rgba(18,37,61,.27)'; ctx.fillRect(0, 0, W, H); ctx.strokeStyle = 'rgba(220,240,255,.32)'; ctx.lineWidth = 3; for (let i = 0; i < 55; i++) { const x = (i * 97 + now * .32) % 2100 - 100, y = (i * 173 + now * .7) % 1200 - 60; ctx.beginPath(); ctx.moveTo(x, y); ctx.lineTo(x - 26, y + 56); ctx.stroke() } } ctx.restore() }
function drawSeaVerification(now) { if (!seaVerifyState) return; const v = seaVerifyState; const p = topTransform(v.target.x, v.target.y); if (v.target.kind === 'lighthouse') { const fl = navLightFlash(now, 0, 5000, 1200); ctx.save(); ctx.translate(p.x, p.y); ctx.fillStyle = '#fff'; rr(-19, -44, 38, 86, 10); ctx.fill(); ctx.fillStyle = '#ff686e'; rr(-25, -54, 50, 16, 8); ctx.fill(); ctx.fillStyle = fl > .4 ? '#fff4a0' : '#68727a'; ctx.shadowColor = fl > .4 ? '#ffe77d' : 'transparent'; ctx.shadowBlur = fl > .4 ? 46 : 0; ctx.beginPath(); ctx.arc(0, -43, 11, 0, TAU); ctx.fill(); if (fl > .4) { ctx.globalAlpha = .18; ctx.strokeStyle = '#fff0a0'; ctx.lineWidth = 20; ctx.beginPath(); ctx.arc(0, -43, 98, 0, TAU); ctx.stroke() } ctx.restore() } else { const fl = navLightFlash(now, 0, 3600, 900); ctx.save(); ctx.translate(p.x, p.y); ctx.fillStyle = '#fff'; rr(-9, -48, 18, 56, 7); ctx.fill(); ctx.fillStyle = '#65dfa0'; rr(-15, -58, 30, 14, 6); ctx.fill(); ctx.fillStyle = fl > .4 ? '#fff3a0' : '#647079'; ctx.shadowColor = fl > .4 ? '#ffe77d' : 'transparent'; ctx.shadowBlur = fl > .4 ? 36 : 0; ctx.beginPath(); ctx.arc(0, -64, 10, 0, TAU); ctx.fill(); ctx.restore() } text('수리 완료 · 정상 점멸', p.x, p.y + 52, 13, '#a8ffd5', 'center', 1000) }

function drawPostRepairExitLine() {
  if (!postRepairExitLine) return;
  const l = postRepairExitLine, nx = -l.hy, ny = l.hx;
  const a = topTransform(l.x + nx * l.halfWidth, l.y + ny * l.halfWidth), b = topTransform(l.x - nx * l.halfWidth, l.y - ny * l.halfWidth);
  ctx.save(); ctx.strokeStyle = '#73d8ff'; ctx.lineWidth = 10; ctx.setLineDash([26, 18]); ctx.shadowColor = 'rgba(115,216,255,.75)'; ctx.shadowBlur = 16; ctx.beginPath(); ctx.moveTo(a.x, a.y); ctx.lineTo(b.x, b.y); ctx.stroke(); ctx.setLineDash([]); ctx.shadowBlur = 0;
  const c = topTransform(l.x, l.y); ctx.fillStyle = 'rgba(24,74,122,.88)'; rr(c.x - 88, c.y - 44, 176, 30, 10); ctx.fill(); text('사무실 복귀 라인 · 약 2,000m', c.x, c.y - 23, 12, '#e8fbff', 'center', 1000); ctx.restore();
}

function drawTop(now) { drawWaterTop(now); drawFaunaTopWater(now); drawRouteTop(); islands.forEach(drawIslandTop); rocks.forEach(drawRockTop); buoys.forEach(b => drawBuoyTop(b, now)); dangerMarks.forEach(m => drawDangerMarkTop(m, now)); drawArrivalCircle(goal.x, goal.y, ARRIVAL_RADIUS, phase === 'return' ? '사무실 귀항 구간' : (goal.kind === 'landing' ? '거문도 선착장 접안 구간' : '도착 구간'), '#79f2cf'); drawTargetTop(now); drawMidRouteBeaconTop(now); drawPostRepairExitLine(); drawWakeTop(); drawShipTop(); drawFaunaTopSky(now); drawFogTop() }

// REAR VIEW SECONDARY
function worldRelative(wx, wy) { const dx = wx - ship.x, dy = wy - ship.y, cs = Math.cos(-ship.heading + Math.PI / 2), sn = Math.sin(-ship.heading + Math.PI / 2); return { x: dx * cs - dy * sn, y: dx * sn + dy * cs } }
function projectRear(rel) { const z = -rel.y; if (z < 120) return null; const scale = 760 / (z + 350); return { x: W * .5 + rel.x * scale, y: H * .39 - z * .025, scale } }
function drawRear(now) {
  let sky = ctx.createLinearGradient(0, 0, 0, H * .42); sky.addColorStop(0, '#65b4d7'); sky.addColorStop(1, '#d3edf2'); ctx.fillStyle = sky; ctx.fillRect(0, 0, W, H * .42); let sea = ctx.createLinearGradient(0, H * .42, 0, H); sea.addColorStop(0, '#207b9c'); sea.addColorStop(1, '#06435f'); ctx.fillStyle = sea; ctx.fillRect(0, H * .42, W, H * .58); ctx.globalAlpha = 1; drawFaunaRearWater(now);
  const objs = [...rocks.map(r => ({ type: 'rock', ...r })), ...buoys.map(b => ({ type: 'buoy', ...b })), ...dangerMarks.map(m => ({ type: 'danger', ...m })), ...(midRouteBeacon ? [{ type: 'target', x: midRouteBeacon.x, y: midRouteBeacon.y, kind: 'beacon' }] : []), { type: 'target', x: goal.x, y: goal.y, kind: goal.kind }]; objs.sort((a, b) => worldRelative(b.x, b.y).y - worldRelative(a.x, a.y).y); for (const o of objs) { const p = projectRear(worldRelative(o.x, o.y)); if (!p || p.x < -200 || p.x > W + 200 || p.y < 220 || p.y > H * .8) continue; if (o.type === 'rock') { ctx.fillStyle = '#55666d'; ctx.beginPath(); ctx.ellipse(p.x, p.y, Math.max(10, o.r * p.scale * .4), Math.max(7, o.r * p.scale * .22), 0, 0, TAU); ctx.fill() } else if (o.type === 'buoy') { const col = o.side === 'red' ? '#ff5962' : '#48db86', s = clamp(p.scale * 2, .4, 2); ctx.fillStyle = col; ctx.fillRect(p.x - 7 * s, p.y - 33 * s, 14 * s, 33 * s); const fl = navLightFlash(now, 0, 3600, 900); ctx.fillStyle = fl > .4 ? '#fff5a0' : '#5b6a72'; ctx.shadowColor = fl > .4 ? '#ffe77d' : 'transparent'; ctx.shadowBlur = fl > .4 ? 24 : 0; ctx.beginPath(); ctx.arc(p.x, p.y - 36 * s, 8 * s, 0, TAU); ctx.fill(); ctx.shadowBlur = 0 } else if (o.type === 'danger') { const s = clamp(p.scale * 2, .45, 1.8); ctx.shadowColor = '#ffd55a'; ctx.shadowBlur = 16; ctx.fillStyle = '#ffd55a'; ctx.beginPath(); ctx.arc(p.x, p.y, 7 * s, 0, TAU); ctx.fill(); ctx.fillStyle = '#17191b'; ctx.fillRect(p.x - 5 * s, p.y - 31 * s, 10 * s, 31 * s); ctx.fillStyle = '#ffd55a'; ctx.fillRect(p.x - 6 * s, p.y - 21 * s, 12 * s, 9 * s); ctx.fillStyle = '#17191b'; ctx.beginPath(); ctx.moveTo(p.x - 8 * s, p.y - 36 * s); ctx.lineTo(p.x, p.y - 49 * s); ctx.lineTo(p.x + 8 * s, p.y - 36 * s); ctx.closePath(); ctx.fill(); ctx.shadowBlur = 0 } else { const s = clamp(p.scale * 2.2, .5, 2); if (o.kind === 'lighthouse') { ctx.fillStyle = '#f4f1e6'; ctx.fillRect(p.x - 12 * s, p.y - 70 * s, 24 * s, 70 * s); ctx.fillStyle = '#d64a4a'; ctx.fillRect(p.x - 17 * s, p.y - 78 * s, 34 * s, 12 * s); const fl = targetLightFlash(now, 'lighthouse'); ctx.fillStyle = fl > .18 ? '#fff5a0' : '#626b72'; ctx.shadowColor = fl > .18 ? '#ffe77d' : 'transparent'; ctx.shadowBlur = fl > .18 ? 28 : 0; ctx.beginPath(); ctx.arc(p.x, p.y - 80 * s, 7 * s, 0, TAU); ctx.fill(); ctx.shadowBlur = 0 } else { ctx.fillStyle = '#eff6f7'; ctx.fillRect(p.x - 7 * s, p.y - 45 * s, 14 * s, 45 * s); const fl = targetLightFlash(now, 'beacon'); ctx.fillStyle = fl > .15 ? '#fff49b' : (o.kind === 'install' ? '#ffd35e' : '#5d6e67'); ctx.shadowColor = fl > .15 ? '#ffe57c' : 'transparent'; ctx.shadowBlur = fl > .15 ? 22 : 0; ctx.beginPath(); ctx.arc(p.x, p.y - 50 * s, 9 * s, 0, TAU); ctx.fill(); ctx.shadowBlur = 0 } } }
  drawFaunaRearSky(now);
  ctx.save(); ctx.translate(W * .5, H * .75); ctx.rotate(ship.rudder * .07); ctx.fillStyle = 'rgba(0,0,0,.25)'; ctx.beginPath(); ctx.ellipse(12, 60, 100, 36, 0, 0, TAU); ctx.fill(); const hg = ctx.createLinearGradient(-80, 0, 80, 0); hg.addColorStop(0, '#d2e1e7'); hg.addColorStop(.5, '#fff'); hg.addColorStop(1, '#c8d7de'); ctx.fillStyle = hg; ctx.beginPath(); ctx.moveTo(0, -115); ctx.lineTo(75, 80); ctx.lineTo(0, 55); ctx.lineTo(-75, 80); ctx.closePath(); ctx.fill(); ctx.fillStyle = '#d84a45'; rr(-38, -20, 76, 48, 10); ctx.fill(); ctx.fillStyle = '#163c50'; rr(-27, -13, 54, 18, 5); ctx.fill(); ctx.restore()
}

function drawMini() { mctx.clearRect(0, 0, 310, 220); mctx.fillStyle = '#061a26'; mctx.fillRect(0, 0, 310, 220); const sx = 310 / world.w, sy = 220 / world.h; mctx.strokeStyle = 'rgba(90,203,242,.16)'; mctx.lineWidth = Math.max(2, routeHalf * 2 * sx); mctx.lineCap = 'round'; mctx.beginPath(); route.forEach((p, i) => i ? mctx.lineTo(p.x * sx, p.y * sy) : mctx.moveTo(p.x * sx, p.y * sy)); mctx.stroke(); mctx.strokeStyle = '#61cfff'; mctx.lineWidth = 2; mctx.beginPath(); route.forEach((p, i) => i ? mctx.lineTo(p.x * sx, p.y * sy) : mctx.moveTo(p.x * sx, p.y * sy)); mctx.stroke(); for (const w of weatherEvents) { mctx.strokeStyle = w.type === 'fog' ? 'rgba(220,235,240,.45)' : w.type === 'highwave' ? 'rgba(111,211,255,.5)' : 'rgba(174,139,255,.5)'; mctx.lineWidth = 1; mctx.beginPath(); mctx.arc(w.x * sx, w.y * sy, Math.max(6, w.r * sx), 0, TAU); mctx.stroke() } for (const r of rocks) { mctx.fillStyle = r.central ? '#d97971' : '#6d767b'; mctx.beginPath(); mctx.arc(r.x * sx, r.y * sy, r.central ? 4 : 3, 0, TAU); mctx.fill() } for (const d of dangerMarks) { mctx.fillStyle = '#f2c84f'; mctx.beginPath(); mctx.arc(d.x * sx, d.y * sy, 3, 0, TAU); mctx.fill() } if (midRouteBeacon) { mctx.fillStyle = midRouteBeacon.status === 'fixed' ? '#7df0bd' : '#ffbf62'; mctx.beginPath(); mctx.arc(midRouteBeacon.x * sx, midRouteBeacon.y * sy, 5, 0, TAU); mctx.fill(); if (midRouteBeacon.status === 'pending') { mctx.strokeStyle = 'rgba(255,191,98,.8)'; mctx.beginPath(); mctx.arc(midRouteBeacon.x * sx, midRouteBeacon.y * sy, Math.max(5, midRouteBeacon.arrivalRadius * sx), 0, TAU); mctx.stroke() } } mctx.strokeStyle = 'rgba(121,242,207,.8)'; mctx.beginPath(); mctx.arc(goal.x * sx, goal.y * sy, Math.max(5, ARRIVAL_RADIUS * sx), 0, TAU); mctx.stroke(); mctx.fillStyle = goal.kind === 'install' ? '#ffd35e' : goal.kind === 'beacon' ? '#68e4a2' : '#ffe08a'; mctx.beginPath(); mctx.arc(goal.x * sx, goal.y * sy, 5, 0, TAU); mctx.fill(); if (postRepairExitLine) { const l = postRepairExitLine, nx = -l.hy, ny = l.hx; mctx.strokeStyle = '#73d8ff'; mctx.lineWidth = 3; mctx.beginPath(); mctx.moveTo((l.x + nx * l.halfWidth) * sx, (l.y + ny * l.halfWidth) * sy); mctx.lineTo((l.x - nx * l.halfWidth) * sx, (l.y - ny * l.halfWidth) * sy); mctx.stroke() } mctx.save(); mctx.translate(ship.x * sx, ship.y * sy); mctx.rotate(ship.heading + Math.PI / 2); mctx.fillStyle = '#6ad4ff'; mctx.beginPath(); mctx.moveTo(0, -8); mctx.lineTo(6, 7); mctx.lineTo(-6, 7); mctx.closePath(); mctx.fill(); mctx.restore(); mctx.fillStyle = '#dbeef7'; mctx.font = '10px sans-serif'; mctx.fillText(goal.name, Math.max(4, goal.x * sx - 38), Math.min(214, goal.y * sy + 16)) }
function drawSail(now) { ctx.save(); if (shake > 0) ctx.translate((Math.random() - .5) * 14 * shake, (Math.random() - .5) * 14 * shake); if (cameraMode === 2) drawRear(now); else drawTop(now); ctx.restore(); drawWeatherScreen(now); drawMini(); ui.inventory.style.display = 'none'; ui.inst.style.display = 'block'; ui.nav.style.display = 'block'; ui.progress.style.display = 'block'; ui.camera.style.display = 'block'; ui.controls.style.display = 'none'; if (ui.mouseControls) ui.mouseControls.style.display = (phase === 'sail' || phase === 'dock' || phase === 'verify' || phase === 'return') ? 'grid' : 'none'; if (flash > 0) { ctx.fillStyle = `rgba(255,255,255,${flash * .22})`; ctx.fillRect(0, 0, W, H) } if (impactTimer > 0) { const a = Math.min(1, impactTimer / .9); const vg = ctx.createRadialGradient(W * .5, H * .5, 120, W * .5, H * .5, W * .7); vg.addColorStop(0, 'rgba(255,80,65,0)'); vg.addColorStop(1, `rgba(255,55,55,${.34 * a})`); ctx.fillStyle = vg; ctx.fillRect(0, 0, W, H); ctx.save(); ctx.translate(W * .5, H * .48); ctx.rotate(-.08); text('쾅!', 0, 0, 78, `rgba(255,245,210,${a})`, 'center', 1000); text('암초와 충돌했습니다', 0, 48, 18, `rgba(255,255,255,${a})`, 'center', 1000); ctx.restore() } }
function draw(now) { if (phase === 'shore' || (phase === 'repair' && currentMission?.id === 'lighthouse' && repairContext === 'main')) drawShore(); else if (phase === 'sail' || phase === 'dock' || phase === 'done' || phase === 'repair' || phase === 'verify' || phase === 'return') drawSail(now); else drawOffice() }
